# Generated by Django 3.2.13 on 2022-10-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=30)),
                ('remarks', models.CharField(max_length=300)),
                ('name_of_identity', models.CharField(max_length=100)),
                ('picture1', models.CharField(max_length=300)),
                ('picture2', models.CharField(max_length=300)),
                ('picture3', models.CharField(max_length=300)),
                ('picture4', models.CharField(max_length=300)),
                ('picture_sc1', models.CharField(max_length=600)),
                ('picture_sc2', models.CharField(max_length=600)),
                ('picture_sc3', models.CharField(max_length=600)),
                ('picture_sc4', models.CharField(max_length=600)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=190)),
            ],
            options={
                'db_table': 'upload_data',
            },
        ),
    ]
