# Generated by Django 3.2.13 on 2022-10-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_uploaddata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddata',
            name='user',
            field=models.CharField(max_length=190, null=True),
        ),
    ]
