# Generated by Django 3.2.13 on 2022-10-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_uploaddata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddata',
            name='user',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
