# Generated by Django 3.2.13 on 2022-10-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_uploaddata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploaddata',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploaddata',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
