# Generated by Django 3.2.13 on 2022-10-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20221004_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddata',
            name='picture1',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='uploaddata',
            name='picture2',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='uploaddata',
            name='picture3',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='uploaddata',
            name='picture4',
            field=models.ImageField(upload_to='images'),
        ),
    ]
