# Generated by Django 3.2.13 on 2022-10-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20221006_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddata',
            name='rel_profile1',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
