# Generated by Django 3.2.13 on 2022-10-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_uploaddata_rel_profile1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddata',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='uploaddata',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='uploaddata',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='uploaddata',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
