# Generated by Django 3.2.13 on 2022-10-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20221007_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddata',
            name='action',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='uploaddata',
            name='action_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='uploaddata',
            name='action_status',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uploaddata',
            name='mlro_remarks',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
