# Generated by Django 3.2.13 on 2022-10-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20221007_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddata',
            name='action_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
