# Generated by Django 2.2.12 on 2022-12-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20221027_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddata',
            name='mlro_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploaddata',
            name='remarks',
            field=models.CharField(max_length=2000),
        ),
    ]
